### PR TITLE
Initial support for script table and media table

### PR DESCRIPTION
**Pull request by centic9**
Some initial work to add script table and media table to the okteta structure using the pointer-feature. The actual play script lines are not parsed yet.

### CODE REVIEW

**Comment by sengels** [comment]
I get some warnings in gmeFile.gmeHeader.mediaFileTableOffset.mediaFileTable.mediaFileTableOffsets[376].mediaFileOffset.mediaFileContent (not only 376 but also others): "new array length is too large (22646), limiting to (10000)"
I am not sure where this comes from, maybe there is a small bug in it.
I'll make a more thorough review tomorrow and merge the request then.
Many many thanks for your work!

**Comment by centic9** [comment]
The warnings are expected currently: I add the binary media files as array of bytes. It seems that Okteta puts a limit of 10000 elements on arrays in order to avoid overwhelming the UI, so if one of the files is larger this warning appears currently.
I can take a look at limiting the number of included bytes as part of the length function for these arrays so the warning does not appear in Okteta...

**Comment by sengels** [comment]
Ok, one more issue: could you transform tabs to spaces in your commits?
you can use this command:
git filter-branch --tree-filter 'git diff-tree --name-only --diff-filter=AM -r --no-commit-id $GIT_COMMIT | find . -exec perl -pi -e "s/\t/    /g" {} \;' HEAD

If you want to work with tabs instead of spaces you can follow this recipe: http://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs

Otherwise this looks nice, the length limit I mentioned yesterday is a restriction from okteta and is an upstream okteta bug.

**Comment by sengels** [comment]
I'll talk to the okteta maintainers, this should be fixed upstream instead (I hope that is ok for you).

**Comment by centic9** [comment]
I have update the tabs/spaces via a new commit, changing git history is probably not a good idea when sharing git repositories on github...

**Comment by sengels** [comment]
Thanks a lot again.

**Pull request merged**
